exclude: "^docs/|/migrations/|/venv/"
default_stages: [pre-commit]


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^migrations/
      - id: end-of-file-fixer
        exclude: ^migrations/
      - id: check-yaml
        exclude: ^migrations/
      - id: check-merge-conflict
        exclude: ^migrations/

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: ^migrations/

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^migrations/

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: ^migrations/
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

ci:
  autofix_commit_msg: |
    🎨 [pre-commit.ci] Auto format from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
