"""add_image_bio_columns

Revision ID: 13bd9f24b789
Revises: 38e1cefad33d
Create Date: 2022-06-11 19:56:47.493415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bd9f24b789'
down_revision = '38e1cefad33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
