"""drop_hashed_password_column

Revision ID: 433e50ed0c1a
Revises: d3da19d98a54
Create Date: 2022-06-04 18:31:27.031625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433e50ed0c1a'
down_revision = 'd3da19d98a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
