"""add_creator_id_to_matches

Revision ID: 792fe30027b5
Revises: d12e4b16c7c7
Create Date: 2022-06-14 14:41:59.166368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '792fe30027b5'
down_revision = 'd12e4b16c7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_creator_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'matches', 'users', ['match_creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'match_creator_id')
    # ### end Alembic commands ###
