"""add_confirmed_column_to_matches

Revision ID: 9aaadc6ada01
Revises: 9ab640b29dbd
Create Date: 2022-06-18 16:43:30.225941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aaadc6ada01'
down_revision = '9ab640b29dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'confirmed')
    # ### end Alembic commands ###
