"""add_pending_confirmation_column_to_matches

Revision ID: 9ab640b29dbd
Revises: 792fe30027b5
Create Date: 2022-06-18 11:48:58.510419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab640b29dbd'
down_revision = '792fe30027b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('pending_confirmation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'pending_confirmation')
    # ### end Alembic commands ###
